version: '3'

services:
  jikan:
    image: jikanme/jikan-rest
    restart: always
    volumes:
      - ./jikan.env:/app/.env
    ports:
      - $JIKAN_PORT:8080

  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_DATABASE

  redis:
    image: redis
    restart: always
