version: '3'

services:
  jikan:
    image: jikanme/jikan-rest
    restart: always
    environment:
      - APP_URL=https://localhost:8080

      - DB_CACHING=true
      - DB_HOST=db
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD

      - CACHING=true
      - CACHE_DRIVER=redis
      - CACHE_METHOD=database

      - REDIS_HOST=redis
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 8080:8080

  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_DATABASE

  redis:
    image: redis
    restart: always
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
