name: my-anime-stats

services:
  app:
    build: .
    restart: always
    environment:
      TZ: Europe/Paris
      LOG_LEVEL: DEBUG
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - 8000:8000
