name: Docker Build Push and Analyze

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Docker Build Push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.14.0
        with:
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  trivy:
    name: Trivy
    runs-on: self-hosted
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy
        run: >
          docker run -v /var/run/docker.sock:/var/run/docker.sock
          aquasec/trivy image --severity CRITICAL,HIGH --pkg-types os,library --format table
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  semgrep:
    name: Semgrep
    runs-on: self-hosted
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config=auto
